# Generated by Django 5.1.7 on 2026-01-21 19:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_email_alter_user_passage_id'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAiQuestion',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserImageAiQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uploader.image')),
                ('user_ai_question_uuid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.useraiquestion')),
            ],
        ),
    ]
