# Generated by Django 5.1.7 on 2026-01-23 19:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_useraiquestion_userimageaiquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskAi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_uuid', models.UUIDField(auto_created=True, default=uuid.uuid4)),
                ('ai_response', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_uuid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.userimageaiquestion')),
            ],
        ),
    ]
