# Generated by Django 5.1.7 on 2026-02-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_askai'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraiquestion',
            name='response',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
