# Generated by Django 5.1.7 on 2026-02-16 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_useraiquestion_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimageaiquestion',
            name='user_ai_question_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_question', to='core.useraiquestion'),
        ),
    ]
