# Generated by Django 6.0.2 on 2026-02-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_userimageaiquestion_user_ai_question_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraiquestion',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
