# Generated by Django 6.0.2 on 2026-03-23 17:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_feed_save_views_like'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGeneration',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('neutral', 'Neutral')], default='neutral', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('image_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uploader.image')),
            ],
        ),
    ]
