# Generated by Django 6.0.2 on 2026-04-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_imagegeneration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegeneration',
            name='feedback',
            field=models.CharField(blank=True, choices=[('like', 'Like'), ('dislike', 'Dislike'), ('neutral', 'Neutral')], default='neutral', max_length=10, null=True),
        ),
    ]
