# Generated by Django 5.1.7 on 2026-04-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_room_useraiquestion_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
