# Generated by Django 6.0.2 on 2026-05-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passage_id',
            field=models.CharField(blank=True, help_text='Passage ID', max_length=255, null=True, unique=True, verbose_name='passage_id'),
        ),
    ]
