# Generated by Django 6.0.2 on 2026-05-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_forgetpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgetpassword',
            name='code',
            field=models.CharField(max_length=255),
        ),
    ]
