import fal_client
from django.conf import settings
import logging

logger = logging.getLogger(__name__)

class ParaFal:
    def __init__(self):
        self.api_key = settings.FAL_API_KEY

    def generate_image(self, prompt):
        try:
            if not prompt or not prompt.strip():
                raise ValueError("Prompt cannot be empty")
            
            result = fal_client.run(
                "fal-ai/nano-banana-2",
                arguments={"prompt": prompt},
                with_logs=True,
                api_key=self.api_key
            )
            
            if not result:
                logger.error("FAL API returned empty result")
                raise ValueError("FAL API returned empty result")
            
            if "images" not in result or not result["images"]:
                logger.error(f"No images in FAL response: {result}")
                raise ValueError("No images generated by FAL API")
            
            image_url = result["images"][0].get("url")
            if not image_url:
                logger.error("Image URL not found in FAL response")
                raise ValueError("Image URL not found in API response")
            
            logger.info(f"Image generated successfully for prompt: {prompt[:50]}...")
            return image_url
            
        except fal_client.exceptions.RequestFailedError as e:
            logger.error(f"FAL API request failed: {str(e)}")
            raise Exception(f"FAL API error: {str(e)}") from e
        except Exception as e:
            logger.error(f"Error generating image: {str(e)}")
            raise